### ISSUE TITLE
`_plot-movement_or_dispersal` plots are inaccurate

### ISSUE THREAD

**Issue by azwadriqbal** [drewhart/geonomics#9]
Hi Drew,

Our group was noticing that the plots for user-defined dispersal/movement parameters were not lining up with those defined in the model params (when set to the same values they would output vastly different plots!) and I think I figured out why:

in `species.py`'s `def _plot_movement_or_dispersal_`:
```
 if distance_distr_param2 is not None:
            setattr(toy_spp,
                    f"{what}_distance_distr_param2",
                    distance_distr_param1,
                   )
```

should be:
```
 if distance_distr_param2 is not None:
            setattr(toy_spp,
                    f"{what}_distance_distr_param2",
                    distance_distr_param2,
                   )
```
Adjusting this locally seems to produce the expected plots! Just wanted to put this on your radar as a quick fix.

**Comment by erthward** [comment]
Thank you for this! Good eye! Fixed in version 1.4.5.
